#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#rodar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opa, erro na tipagem em um arquivo, corriga o problema!"
    exit 1;
fi;

# formatar cada arquivo alterado
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

for FILE in $STAGED_FILES
do
    # sail pint "${FILE}"
    git add "${FILE}"
done;
