#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#rodar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opa, erro na tipagem em um arquivo, corriga o problema!"
    exit 1;
fi;

PROJECT=`php -r "echo dirname(dirname(realpath('$0')));"`